### ISSUE TITLE
Providing a context provider

### ISSUE THREAD

**Issue by matinzd** [dabakovich/react-native-controlled-mentions#101]
I think it can be a good idea to provide a context provider in order to move suggestion rendering out of the container itself. 
Imagine you are having a comment input and a send button next to it. For example:

<img width="388" alt="Screenshot 2022-09-02 at 15 28 00" src="https://user-images.githubusercontent.com/24797481/188156171-53215286-1d56-46e0-ac19-bb50ea97c8fc.png">

**Comment by fukemy** [comment]
why not use scrollView?

**Comment by matinzd** [comment]
> why not use scrollView?

What do you mean?

**Comment by fukemy** [comment]
i think better is keep rendering view inside mentionView better(avoid memories, better handling). And you can wrap the mentionView by scrollView + give maxheight to it.

But for your issues, you can refer to v3 alpha then look how it work

**Comment by matinzd** [comment]
> i think better is keep rendering view inside mentionView better(avoid memories, better handling). And you can wrap the mentionView by scrollView + give maxheight to it.
> 
> But for your issues, you can refer to v3 alpha then look how it work

I mean we can move rendering the whole list out of component and have some kind of context to get the render suggestions. 
I may send a PR for my proposal.

**Comment by fukemy** [comment]
Please double check the v3-alpha, hi did all your purpose.
1. No neer to use MentionInput directly
2. Keep track to mentions suggest
3. Render mention view in every place you want

**Comment by fukemy** [comment]
https://github.com/dabakovich/react-native-controlled-mentions/issues/75#issuecomment-1114282123

**Comment by matinzd** [comment]
> #75 (comment)

Nice! I didn’t see that. 
That is what I wanted :)

**Comment by dabakovich** [comment]
Closing the issue as it seems that v3 resolves the issues described here.
