### ISSUE TITLE
onSuggestionPress does not work

### ISSUE THREAD

**Issue by LouisSyfer** [dabakovich/react-native-controlled-mentions#102]
Hi everyone,

The package works fine except when I select the value (mention or hashtag). It returns "undefined" inside the textinput. Whatever I do, whatever the platform. Please I'd like to know if anybody else got this issue, and how to fix it... ?

Thanks in advance for the reply.

**Comment by dzaiats** [comment]
Hi @LouisSyfer as I understood - it is kind of a feature. Make sure that your data (json) is structured into {name: "smthing", id: number}. `name` and `id` are mandatory parts of the data.

**Comment by LouisSyfer** [comment]
Hi @dzaiats 

I modified the properties in utils/types files. It's easier, and flexible. 

Thanks for your reply !

**Comment by dabakovich** [comment]
The question seems to be over. Closing issue.
