### ISSUE TITLE
Double Input on React Native 0.70.1

### ISSUE THREAD

**Issue by gelodgreat** [dabakovich/react-native-controlled-mentions#104]
We upgraded our app and found that there's an issue with this library even in alpha version.

Every time the user input @ it became @@, Also when pressing space the current text got doubled. This might be because of changes in TextInput?

**Comment by hamdij0maa** [comment]
Having the same issue, after upgrading RN to 0.70.1 the value is repushed on key press  ( bug)

**Comment by moseffect21** [comment]
+1

**Comment by wfern** [comment]
This bug was not originated from this library, it was introduced on react-native 0.70.0 and was fixed on 0.70.3

**Comment by gelodgreat** [comment]
Thanks, this was resolved on 0.70.3
