### ISSUE TITLE
how to pass textInputProps 

### ISSUE THREAD

**Issue by ArjunPatidarRadix** [dabakovich/react-native-controlled-mentions#106]
How can i pass `textInputProps`, like I need to pass the `RightIcon` Props to this component, Thanks

**Comment by Svarto** [comment]
Just pass the righticon as a prop like normal. You are deconstructing the textInputProps, which includes onChangeText, onSelectionChange and children. You can then add any other Props you want to the TextInput.

**Comment by dabakovich** [comment]
I'm closing the issue due to the lack of new questions and activity.

You are welcome to add comments or create an issue if you'll get new questions.
