### ISSUE TITLE
How to restrict enter and other special character like space

### ISSUE THREAD

**Issue by codal-mpawar** [dabakovich/react-native-controlled-mentions#107]
@dabakovich @ein1x3x 
"react-native-controlled-mentions": "^3.0.0-alpha.4"

We are using the above version in our app. how can we restrict the enter, space, and other special characters in suggestions?

**Comment by dabakovich** [comment]
Hey @codal-mpawar!

Is your issue still actual? If so, please share a few examples where you're having difficulties.
