### ISSUE TITLE
inputRef undefined for Mentions

### ISSUE THREAD

**Issue by Abhishek-Sankey** [dabakovich/react-native-controlled-mentions#11]
I've declared a reference for `Mentions` as below:
`inputRef={ref => {
	this.mentionsInput = ref;
}}`

when i print this ref on click of a button then it's showing as undefined.
Not sure, if I'm doing something wrong. Can someone plz help?
Thanks!

**Comment by dabakovich** [comment]
I was working with functional components so that's why `inputRef` doesn't support functional refs.
Will deploy an update soon.

**Comment by dabakovich** [comment]
Fixed in v0.1.8

**Comment by anhquan291** [comment]
> Fixed in v0.1.8

Thank you so much for this useful library. It deserves 1000 stars :D!
