### ISSUE TITLE
Adding multiline prop to TextInput creates flickering for suggestions list

### ISSUE THREAD

**Issue by andreirat** [dabakovich/react-native-controlled-mentions#110]
I'm using the latest version of this component (3.0.0-alpha.4) and I have the following issue: 

If I add the `multiline` prop to `TextInput` it will cause a flicker for the suggestions list. This is happening because the `keyword` is undefined even if it shouldn't be. But, it changes to the value typed in the input shortly. 

Another issue is that there are multiple re-renders. You can see in the screenshot attached that each time I press a key, the `keyword` is `undefined` and then re-rendered twice.  

Any ideas on how to fix this? 
Thanks.
<img width="507" alt="Screenshot 2023-01-26 at 09 56 54" src="https://user-images.githubusercontent.com/17424445/214785076-99a106b1-1a02-47fa-a07c-1bebc3fab7af.png">

https://user-images.githubusercontent.com/17424445/214785110-9d45413b-a8f4-41c7-b288-17d6adb3eaef.mp4

**Comment by stevewillard** [comment]
@andreirat did you happen to find a solution for this?
