### ISSUE TITLE
 Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

### ISSUE THREAD

**Issue by Slicefresh22** [dabakovich/react-native-controlled-mentions#114]
I am seeing this warning/error coming from this library. Any idea what's going on here?

**Comment by dabakovich** [comment]
Please try to play with the [alpha v3.0.0](https://github.com/dabakovich/react-native-controlled-mentions/tree/3.0) version of the library, which uses a hook that passes props to your native `TextInput` component.
