### ISSUE TITLE
Using emojis breaks formatting

### ISSUE THREAD

**Issue by youngzodiac** [dabakovich/react-native-controlled-mentions#122]
If I enter emojis and text after a hashtag, then keep using hashtags further down in my post, the hashtags will begin to not terminate their sequence and all the text entered will become my hashtag color.

**Comment by dabakovich** [comment]
Hey @youngzodiac, thanks for your feedback!

Is the issue still actual? If so, did you play with our [pre-release third version](https://github.com/dabakovich/react-native-controlled-mentions/releases/tag/v3.0.0-alpha.2) of the library? Many similar issues are not reproducing in this version.

**Comment by youngzodiac** [comment]
The pre-release is great! This fixed many issues. I was going to fork it so I could get more control of rendering suggestions,  but you already did it. I wish I had seen this branch before.... 

Thank you so much for this library; my app is about to go to production with it.

**Comment by dabakovich** [comment]
I'm glad to hear that. In any case, I suggest you thoroughly test this version of the library to ensure it covers all your cases well. After all, it's still a pre-release version and may contain some bugs. For example, pay attention to #112 and #89.

I'm closing this issue for now. You are welcome to ask additional questions or create a new issue if needed.
