### ISSUE TITLE
Suggestion: Add URL formatting

### ISSUE THREAD

**Issue by snamstorm** [dabakovich/react-native-controlled-mentions#13]
We're using `react-native-parsed-text` library to show the hashtags and URL formatting. We only highlight the URL by changing its style(no hiding the link).

The regEx used for URL: 
1. Short: `/\bhttps?:\/\/\S+/gi`
2. Long: `/(https?:\/\/|www\.)[-a-zA-Z0-9@:%._\+~#=]{1,256}\.(xn--)?[a-z0-9-]{2,20}\b([-a-zA-Z0-9@:%_\+\[\],.~#?&\/=]*[-a-zA-Z0-9@:%_\+\]~#?&\/=])*/i`

Below is the screenshot of the TextInput which I'm using:

![Screenshot 1942-10-07 at 5 46 28 PM](https://user-images.githubusercontent.com/10230039/103214552-ac7a4080-494b-11eb-88c8-b0870a0da0e4.png)

**Comment by snamstorm** [comment]
@dabakovich just wondering if you will be looking at this anytime soon please? Thanks!

**Comment by dabakovich** [comment]
Hey @snamstorm! The feature is available now on alpha 2.0.0-0. Please test it and tell me if you'll get any issues.

**Comment by snamstorm** [comment]
@dabakovich thanks - tested and this works well.

Can we merge to master branch and make a new release please?

**Comment by dabakovich** [comment]
Sure, v2.0.0 is now available for download. Please close the issue if you don't have any other questions.

**Comment by antochan** [comment]
@snamstorm why is it that using your short regex `/\bhttps?:\/\/\S+/gi` the matched text actually just automatically gets deleted.

https://github.com/dabakovich/react-native-controlled-mentions/assets/23144735/769483fd-add0-47e7-b4b0-6a1ad47a5ed9
