### ISSUE TITLE
Need example of using remote API for suggestion population

### ISSUE THREAD

**Issue by ScottWallace** [dabakovich/react-native-controlled-mentions#16]
Component looks great. Seems like the most-used case for suggestions population is from a remote API. Can you provide an example of that?

**Comment by dabakovich** [comment]
Thanks for your feedback.
Actually, the suggestion list is fully controlled by you. `renderSuggestions` in the readme is just example. You can pass there any class/functional component you prefer with any kind of suggestion list (either locally hardcoded or provided from store).

**Comment by Svarto** [comment]
@ScottWallace Sharing how I made it work:

RenderSuggestion:
```
  const renderUserSuggestions = ({ keyword, onSuggestionPress }) => {
    if (keyword == null) {
      return null;
    }

    // This updates the state of the keyword and fires off the search to remote DB
    debouncedSearch(keyword);

    if (fetching || data == undefined) {
      return (
        <View style={{ padding: 12 }}>
          <Loader />
        </View>
      );
    }
      <View
        style={{
          overflow: "visible",
          backgroundColor: "transparent",
        }}
      >
        {data.search_user_mentions.map((user, index) => {
      <Your custom component showing each result>
        })}
      </View>
    );
  };
```

Debounce function:
```
  const debouncedSearch = useCallback(
    debounce((keyword) => {
      setPauseQuery(false);
      setSearchText(keyword);
    }, 500),
    []
  );
```

And I use graphQL with URQL, so this will depend how you want to handle it but the debounceSearch inserts the keyword into state so whatever remote DB API you are using should be firing off at this point:
```
  const [searchText, setSearchText] = useState("");
  const [pauseQuery, setPauseQuery] = useState(true);

  const [result, reexecuteQuery] = useQuery({
    query: SEARCH_USER_MENTIONS,
    variables: {
      search: searchText,
    },
    pause: pauseQuery,
  });
  const { data, error, fetching } = result;
```

It is probably not perfect but might help you a bit on the way to make this work with a remote DB solution.

**Comment by ScottWallace** [comment]
@Svarto, perfect, very helpful, thanks!

**Comment by dabakovich** [comment]
The question seems to be over. Closing issue.
