### ISSUE TITLE
replaceMentionValues mixup name and id

### ISSUE THREAD

**Issue by dngconsulting** [dabakovich/react-native-controlled-mentions#19]
Following the documentation, this code should work 

`console.log(replaceMentionValues(value, ({id}) => `@${id}`)); // Hello @5! How are you?`

But it returns /`/ Hello @David ! How are you?`

v2.0.1

**Comment by dabakovich** [comment]
Thanks for your feedback!
Are you sure you used v2.0.1? Because actually, that bug was present in v2.0.0 and fixed in v.2.0.1.

**Comment by dngconsulting** [comment]
Sorry my bad. When I saw that you have fixed the bug I have upgraded to 2.0.1, deleted the 2.0.0 and restart Metro. But as usual with Metro, it was somewhere in the cache. I had to change manually the src files in node_module in order to get the cache refreshed. Thanks for you quick answer @dabakovich and Bravo for this really useful component. I close the ticket.
