### ISSUE TITLE
Mention rendering won't work when ID contains special chars

### ISSUE THREAD

**Issue by dngconsulting** [dabakovich/react-native-controlled-mentions#21]
Hi,

When I use the normal sample with ID containing string like '1', '2' the mention renderer works well. 

But our ID are complex and generated by a technical DB (Graph database). This kind of ID looks like `AA:108123997020226186155@domain.com`. In this case the renderer messes up and displays the original text pattern this way => `@[THE NAME](AA:108123997020226186155@domain.com)` instead of rendering it with the name.

Easy to reproduce, just change the ID value adding special chars.

**Comment by dabakovich** [comment]
Hey, thanks for the feedback!
I see. I'll think about modifying the regex to make it possible to use some other characters in ID field.

**Comment by dngconsulting** [comment]
Thanx for your quick answer. The workaround is to convert all backend coming IDs in Hexadecimal (with NodeJS Buffer class), pretty ugly but it works 😄

**Comment by dabakovich** [comment]
Fixed in v2.0.2.
Please feel free to check it and open the ticket again if you will get any problems.

**Comment by dngconsulting** [comment]
That works perfectly, thanks @dabakovich   🙏
