### ISSUE TITLE
Clicking suggestion dismisses keyboard

### ISSUE THREAD

**Issue by andywong418** [dabakovich/react-native-controlled-mentions#22]
Right now when I click a suggestion the keyboard is dismissed and I have to re-focus on the text input programmatically. Is there any way around this?

**Comment by andywong418** [comment]
Turns out this was a scroll view issue - https://github.com/facebook/react-native/issues/4229. Closing

**Comment by SeanRoberts** [comment]
Shortcut for anyone with the same issue: if you've got your mentions in a ScrollView add `keyboardShouldPersistTaps="always"` to it

**Comment by youngzodiac** [comment]
@SeanRoberts this worked, thank you! Hope this saves someone else all the time I spent debugging this.
