### ISSUE TITLE
App can't start when add this library (ios < 12).

### ISSUE THREAD

**Issue by hoangsang0109** [dabakovich/react-native-controlled-mentions#23]
Hi Dabakovich, I am very thankful for this library, but currently I am facing a problem. I can't start project on ios < 12, i have tried research, it seems to be related to regex: 
`/(?<original>(?<trigger>.)\[(?<name>[^[]*)]\((?<id>[^[]*)\))/gi`

Can you help me to solve this problem? Thanks.

This is screenshot (iPhone 6s Plus - 10.3.1):
![Simulator Screen Shot - iPhone 6s Plus - 2021-01-25 at 13 54 51](https://user-images.githubusercontent.com/26006412/105674984-ed4d8100-5f1a-11eb-94b9-5ffd06548508.png)

**Comment by dabakovich** [comment]
Hi @hoangsang0109! What RN version are you using?

**Comment by Sendhuraan** [comment]
I'm also facing a similar issue. App crashes on start when using the library. Any suggestions ?

**Comment by dabakovich** [comment]
Thanks for your feedback!
What platform and RN version are you using? What error are you getting?

**Comment by Sendhuraan** [comment]
> Thanks for your feedback @Sendhuraan!
> What platform and RN version are you using? What error are you getting?

I'm using IOS and RN version is 0.63.2

**Comment by hoangsang0109** [comment]
> Hi @hoangsang0109! What RN version are you using?

I'm using RN versions both 0.61.5 and 0.63.3. According to my research: **Named capture groups** of regex are not supported on version iOS < 11.0.0 (But when I used iOS 11.1 it also crashed).

**Comment by dabakovich** [comment]
@hoangsang0109 thanks for your research!
I came to a similar conclusion.
Will try to do something with this soon.

**Comment by kirillrevasiliev** [comment]
@Sendhuraan @hoangsang0109 
you need to add @babel/plugin-transform-named-capturing-groups-regex to babel plugins

**Comment by dabakovich** [comment]
Hi all!
I replaced named capture groups with simple capture groups. Can you check if it fixed your issue?
The fix is published as npm alpha v2.2.4-0 release.

**Comment by hoangsang0109** [comment]
> Hi all!
> I replaced named capture groups with simple capture groups. Can you check if it fixed your issue?
> The fix is published as npm alpha v2.2.4-0 release.

Hi @dabakovich, I try 2.2.4-1 and it work very well, thank you so much.

**Comment by dabakovich** [comment]
Just published the v2.2.4 release with the fix.

I'm going to close the issue.
Feel free to re-open the issue if you will get some issues.
