### ISSUE TITLE
Impossible to use parenthesis "("  

### ISSUE THREAD

**Issue by dngconsulting** [dabakovich/react-native-controlled-mentions#24]
@dabakovich We have a problem probably related to the regEx as parenthesis are used to specify the ID. When we type '(' followed by  some text, the word disappears. To reproduce it, just use the sample provided in the repository and type "(" followed by an other text.

Do you think it can be fixed very soon ?

Thanks.

**Comment by dabakovich** [comment]
Can you provide me the exact text that you typing in?

**Comment by dngconsulting** [comment]
Sure. I have taken the repo sample and after `Hello @[Mary](2)! How are you? ` I add (test). The text `(test)` disappears.

**Comment by dabakovich** [comment]
Fixed in v2.0.3. Please feel free to re-open the ticket if the bug will appear again.

**Comment by VickyStash** [comment]
@dabakovich I have a similar issue in v2.1.0, when I type ")" words disappear

**Comment by dabakovich** [comment]
@VickyStash thanks for your feedback!
Can you provide me an exact string that causes the error?

**Comment by VickyStash** [comment]
@dabakovich
`@[Vik](2) great :) `
After typing ")" all words beside mention disappear

**Comment by dabakovich** [comment]
Oh, I see. Will try to fix it soon.
Probably I should add classic emojis to the test cases :)

**Comment by dabakovich** [comment]
@VickyStash fixed it locally.
Need to wait for confirmation from the guys in #23 then I'll push a fix for that.

**Comment by VickyStash** [comment]
@dabakovich Is there a chance to get a fix today?

**Comment by dabakovich** [comment]
@VickyStash Not sure if it will be released today.
But I can publish a prerelease alpha version with the fix.

**Comment by VickyStash** [comment]
@dabakovich Yes, please

**Comment by dabakovich** [comment]
@VickyStash please, test it on npm v2.2.4-1 alpha prerelease :)

**Comment by dabakovich** [comment]
@VickyStash just published the v2.2.4 release with the fix.

I'm going to close the issue.
Feel free to re-open the issue if you will get some issues.
