### ISSUE TITLE
Changing the behaviour of "space" when selecting a mention

### ISSUE THREAD

**Issue by emmanuelefort** [dabakovich/react-native-controlled-mentions#25]
Thanks for this great module.

We are using the mentions in a pretty large universe where the number of "hits" can be very large, and one thing that would be very useful is that we can query sentences instead of single words (ie multiple words separated by a space).

For ease of clarity, in the examples below I will use _ as space.

Currently when the user types space, it stops the mention searching and leaves the mention as plain text. For example if I type @emmanuel_ then the result will be @emmanuel in plain text.

A more useful handling of typing space would be for us to:
- keep searching after the space e.g. @emmanuel_lef...
- if the query doesn't return anything after the user has typed space: leave the mention as plain text. e.g. @emmanuel_lefoart_ would yield plain text (note the space after "lefoart_") because there is no exact match for "emmanuel lefoart".
- if the query returns exactly one result after the user has typed space: take this result.
- if the user picks up a result in the list, take that result
- if the user back spaces while the search is still ongoing: search with the current text: e.g. @emmanuel_le...
- if the user back spaces on the plain text version: NOTHING happens until the user reaches the part that has no space: e.g. @emm.... **(same as current behaviour)**
-  if the user back spaces on an active mention (the highlighted part): keep on doing the search for the entire text **(current behaviour is that the part after any space is dropped)**

Let me know if this makes any sense !
Thanks.

**Comment by dabakovich** [comment]
Thanks for your feedback and very detailed explanation of the problem!
Yes, it really makes sense, I thought about this earlier but didn't have time to change this flow.
I will think about how to implement the improvement. However, you can try to make that by yourself and then create a PR.

**Comment by emmanuelefort** [comment]
Thanks for your swift reply - would love to but I'm not really a developer :)

**Comment by dabakovich** [comment]
Ok, got it.
So hopefully I'll get some time in the nearest future to implement this improvement.

**Comment by emmanuelefort** [comment]
Awesome - that would be super useful.

**Comment by dabakovich** [comment]
Hey! Just publish an alpha v2.2.0-0 for your testing.
I simply allowed spaces in the mention part type keyword (you can control this by `allowedSpacesCount` in part type object that is `1` by default).

Please test it and give me feedback is that enough for you.

**Comment by emmanuelefort** [comment]
Thanks @dabakovich !! We will have a look asap.

**Comment by emmanuelefort** [comment]
Hey ! Would you mind updating the version in Snack so I can play with it there ? Thanks !!

**Comment by dabakovich** [comment]
@emmanuelefort you can play with that in the expo snack now.

**Comment by emmanuelefort** [comment]
Thanks again for the new feature - I think we are almost there. However one small bug / behaviour issue: it should stop searching for matching mentions once the user has selected a mention. See attached video. Is the change possible ? Searching should resume only when the user deletes inside the existing mention.

https://user-images.githubusercontent.com/53368615/108455068-84062700-72a8-11eb-9803-d0cae87c1ae0.mp4

**Comment by emmanuelefort** [comment]
Another (non related) question: what would be the best way for the suggestion box to only appear when the user types the trigger symbol ? We are using your component in a note taking context and our text typing area is at the top os the screen, down to the keyboard. Ideally the suggestion box would "pop up" (ie push the text area upwards) only when the user hits the trigger, and disappear when the user has selected the mention they want.

**Comment by dabakovich** [comment]
Thanks for reporting about the serious bug. Fixed it in v2.2.0-1. The version is already included in the snack from the readme. Please, try it now.

**Comment by dabakovich** [comment]
Didn't catch the problem in your last comment. Can the `isBottomMentionSuggestionsRender` prop help you in this case?

**Comment by emmanuelefort** [comment]
> Thanks for reporting about the serious bug. Fixed it in v2.2.0-1. The version is already included in the snack from the readme. Please, try it now.

It works well, many thanks !

**Comment by emmanuelefort** [comment]
> Didn't catch the problem in your last comment. Can the `isBottomMentionSuggestionsRender` prop help you in this case?

Basically would like to have the mentions box disappear and reappear only when the user types @ or # so we can use the space for other stuff like a larger input box, or chats etc.

**Comment by dabakovich** [comment]
Firstly, you can actually handle when the user typed trigger symbol ("@" or "#"), because in that case `keyword != null` but empty string ('').
And lastly, as I understood you want to transform the typing input in a case when `keyword` is not undefined and put it to the very top of the screen with suggestions under the input area?
One of the solutions is to play with the Portal pattern in React Native (for example this component from react-native-paper).
If I didn't catch your problem correctly, provide me some code or mockups or examples of the existing apps of what you need to implement.

**Comment by dabakovich** [comment]
@emmanuelefort  do you have any other questions there?

**Comment by dabakovich** [comment]
I'm going to close the issue.
Please, feel free to re-open it if you will get any other questions.
