### ISSUE TITLE
Link doesnt have onPress

### ISSUE THREAD

**Issue by csetyawan** [dabakovich/react-native-controlled-mentions#26]
Would you create onPress on the link

**Comment by dabakovich** [comment]
Hey, thanks for your feedback!
Do you mean pressable formatted link directly in text input?

**Comment by csetyawan** [comment]
Link should be pressable.
When user press the link, user can determine what they will doing.
Its more flexible

**Comment by csetyawan** [comment]
> Hey, thanks for your feedback!
> Do you mean pressable formatted link directly in text input?

yes, the pressable is in text input

**Comment by dabakovich** [comment]
Unfortunately, it's not possible using native components and props.

**Comment by dabakovich** [comment]
I'm going to close the ticket. Please feel free to open it again if you will get any other questions on the topic.

**Comment by csetyawan** [comment]
it s possible to add <a> or <Link> to our url ? so we can click the url

**Comment by dabakovich** [comment]
Unfortunately, that doesn't work that way on mobile apps.
Did you ever see this feature in any mobile messenger app? :)
