### ISSUE TITLE
How can we display Suggestion list at the bottom of the MentionInput instead of always top?

### ISSUE THREAD

**Issue by supreetuf** [dabakovich/react-native-controlled-mentions#27]
The suggestion list always opens up at the top of the input. Can we change its position?

![Screenshot 2021-02-11 at 2 55 19 PM](https://user-images.githubusercontent.com/12533816/107619427-2acf3f80-6c79-11eb-88d2-c1d55f6475f3.png)

**Comment by dabakovich** [comment]
Thanks for your feedback!
I see it makes sense. I have an idea and will try to implement it soon.

**Comment by supreetuf** [comment]
That's great! Will be looking forward to it.

**Comment by dabakovich** [comment]
Just published v2.1.0 with the new `isBottomMentionSuggestionsRender` property that you can define in your mention part type. So those mention suggestions will be rendered just after the input.

Please check it and close the issue if all is ok.

**Comment by supreetuf** [comment]
Works like a charm! Thanks a lot for the quick update.
