### ISSUE TITLE
isBottomMentionSuggestionsRender not working 

### ISSUE THREAD

**Issue by ruchikaAxis** [dabakovich/react-native-controlled-mentions#28]

**Comment by dabakovich** [comment]
Thanks for your feedback!
What RN library version are you using?
How did you declare the MentionInput component (provide me this place in code, please)?

**Comment by dabakovich** [comment]
Hi @ruchikaAxis!
I'm going to close the ticket due to the inactivity.
Feel free to re-open it again when you will get any additional info.
