### ISSUE TITLE
Typing out name without tapping suggestion

### ISSUE THREAD

**Issue by maxhudson** [dabakovich/react-native-controlled-mentions#30]
If you type out a name @Mike but don't tap the @Mike suggestion, it is not registered as a suggestion

**Comment by dabakovich** [comment]
Thanks for your feedback @maxhudson!
Sorry, I didn't really catch the issue here?
Because actually it's expected behavior. It allows us for example add multi-word mentions ("@Mike Black"). If a user didn't tap the suggestion then he doesn't want to capture this mention.
