### ISSUE TITLE
parseValue is not a function

### ISSUE THREAD

**Issue by chloehjung15** [dabakovich/react-native-controlled-mentions#34]
When I try to use 'parseValue' it comes up with an error saying "TypeError: (0 , _reactNativeControlledMentions.parseValue) is not a function".
I think it might not be exported?
Thanks!

**Comment by dabakovich** [comment]
Hi @chloehjung15!
Hmm, It's exported actually.

What library version are you using?
Is any other helper importing successfully (`mentionRegEx` or `replaceMentionValues`)?
Can you provide me a code example of how are you trying to import and use this helper?

**Comment by rjacoby15** [comment]
I am having the same issue using version 2.2.0

here is my import
`import {
  Part,
  PartType,
  parseValue,
  isMentionPartType,
  replaceMentionValues
} from 'react-native-controlled-mentions';`

replaceMentionValues is working for me though.

**Comment by dabakovich** [comment]
That's very strange.

Try to clean your npm cache, maybe the problem is there.

**Comment by chloehjung15** [comment]
'replaceMentionValues' is also working for me as well. It's just 'parseValue'.
I'm also using v2.2.0
I don't actually need this function now but I found that the function works by adding this line of code at the end of the `dist/index.js` file

`Object.defineProperty(exports, "parseValue", { enumerable: true, get: function () { return utils_1.parseValue; } });`

**Comment by dabakovich** [comment]
Sorry @chloehjung15, @rjacoby15 it was my mistake.
As it turned out, for some reason I did not export this function in the `index.ts`.

I'll publish a patch update for that.
