### ISSUE TITLE
Hitting submit key triggers onSubmitEditing and onChange

### ISSUE THREAD

**Issue by dbhathena** [dabakovich/react-native-controlled-mentions#35]
I'm using this for a standard chat app, and when hitting "return" (or "send") on the keyboard does trigger the onSubmitEditing callback (the message sends) but the text in the input persists and a carriage return is added to the text. I even clear the state for the value prop in the onSubmitEditing callback, with no luck. Any suggestions? Code below

MentionInput code:
```
<MentionInput
        onSubmitEditing={this.submitNewMessage}
        value={this.state.newMessage}
        onChange={text => this.setState({newMessage: text})}
        placeholder="Send a message..."
        returnKeyType="send"
        containerStyle={styles.inputContainer}
        partTypes={[
            {
                trigger: '@',
                renderSuggestions: this.renderUserSuggestions,
                textStyle: {fontWeight: "600", color: '#0F1C44'}
            }
        ]}
    />
```

submitNewMessage code (redacted and simplified):
```
submitNewMessage = event => {
        const newMessageData = {<Message Data Here>};
        sendMessage(newMessageData)
            .then(this.setState({newMessage: ""}))
    };
```

**Comment by dbhathena** [comment]
Following up with some more information:

- using the `inputRef` prop and and calling `current.clear()` on that ref in the submit callback also does not work
- the `value` prop does not seem to accomplish what its spec implies (it is not the same as in `TextInput`). For `TextInput` the input's value is constantly controlled by the provided `value` prop. for `MentionInput` it seems the `value` prop only sets the initial input text state, which is then allowed to change however it likes afterwards. This violates what the `value` prop is intended to do

**Comment by dabakovich** [comment]
Thanks for your feedback!
Yes, I agree that `MentionInput`'s `value` just imitates the behavior of the original value.
But I think you stuck with the issue due to the hardcoded `multiline` property for the `TextInput` in the library.

I'll publish a patch update that should fix this.

**Comment by dbhathena** [comment]
@dabakovich I saw the change you made and have updated the package in my project, but I haven't noticed any difference. setting multiline to true still results in a submit that calls `onChange` and `onSubmitEditing` at the same time. Any help would be appreciated!

**Comment by dabakovich** [comment]
As I understood, in your case you want to send a message right after the "Return" press, correct?
So you need to disable the `multiline` property.

**Comment by dbhathena** [comment]
Thanks for the tip! I was hoping to be able to send when hitting "Return", but also wanted the message box increase in height to fit the text being sent if it overflows to multiple lines. I realize that is not what multiline means though, so I just added a "send" button next to the text box to send the message. Appreciate the help!
