### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'text.length')

### ISSUE THREAD

**Issue by Abhishek-Sankey** [dabakovich/react-native-controlled-mentions#36]
Hey,
I have a form where a user can add multiple fields and one of them is using `MentionInput` which is not a required field.
When I try to edit the form then I'm getting the below error:
![Screenshot 1942-12-06 at 3 50 04 PM](https://user-images.githubusercontent.com/53463010/109139813-ee740700-7781-11eb-87a1-86fb54d1f18b.png)

I looked into the code and found the issue. It's in `generatePlainTextPart` method. When i put a null check for the text then it works fine...
Can you plz look into this? I can create a PR for same

Thanks!

**Comment by dabakovich** [comment]
Thanks for your feedback!
Got it, I'll make a new patch update later for this.

**Comment by Abhishek-Sankey** [comment]
@dabakovich I've updated the lib to 2.2.3 but still getting the same error...
const generatePlainTextPart = (text, positionOffset = 0) => ({
    text,
    position: {
        start: positionOffset,
        end: positionOffset + text.length,   // this text is coming as undefine here
    },
});

this is in utils.js file..

**Comment by Abhishek-Sankey** [comment]
@dabakovich any update on this?

**Comment by dabakovich** [comment]
Not yet.
Please, feel free to create a PR and I will check it.

**Comment by Abhishek-Sankey** [comment]
okay, will create a PR for same

**Comment by Abhishek-Sankey** [comment]
@dabakovich created a pull request(https://github.com/dabakovich/react-native-controlled-mentions/pull/39) for the same. Plz do let me know if you find anything wrong in PR.

**Comment by dabakovich** [comment]
Should be fixed in v2.2.4.
I'm going to close the issue.
Please check it and feel free to re-open the issue if you will get some issues.
