### ISSUE TITLE
Bug: android on hermes 

### ISSUE THREAD

**Issue by beqramo** [dabakovich/react-native-controlled-mentions#37]
Hi,

on android with Hermes, there is a problem with regex 
``
SyntaxError: 268576:22:Invalid regular expression: Quantifier has nothing to repeat, js engine: Hermes
``

because Hermes doesn't support named capture groups yet https://github.com/facebook/hermes/issues/89

and as I see you are using it here: https://github.com/dabakovich/react-native-controlled-mentions/blob/c4374946ea26013130bef7314f73d6527a08ce18/src/utils/utils.ts#L7

**Comment by dabakovich** [comment]
Thanks for your feedback!
I replaced named capture groups with simple capture groups. Can you check if it fixed your issue?
The fix is published as npm alpha v2.2.4-0 release.

**Comment by beqramo** [comment]
thanks, I will check it tomorrow.

**Comment by beqramo** [comment]
done. it works. I'm closing it.

**Comment by dabakovich** [comment]
Just published the v2.2.4 release with the fix.
