### ISSUE TITLE
is possible trigger from multiple chars ? 

### ISSUE THREAD

**Issue by bayaroch** [dabakovich/react-native-controlled-mentions#51]
How can i trigger renderSuggestion from multiple trigger characters like single-byte @ and double byte ＠

**Comment by dabakovich** [comment]
It will be available in next v3 release.

Duplicates #38, let's continue discussion there.

**Comment by dabakovich** [comment]
I'm glad to say that v3 release is coming with few core improvements. One of the new features is full support of multiple characters trigger and custom regex pattern for mentions.

You can find examples of using new v3 release here: https://github.com/dabakovich/react-native-controlled-mentions/blob/3.0/example/mentions-functional-component.tsx

To test `alpha` pre-release please, install the library using next command:
```
yarn add react-native-controlled-mentions@alpha
// or
npm install --save react-native-controlled-mentions@alpha
```
