### ISSUE TITLE
Question - is it possible to use my own component for rendering suggestions?

### ISSUE THREAD

**Issue by Abhishek-Sankey** [dabakovich/react-native-controlled-mentions#7]

**Comment by dabakovich** [comment]
Sure. Actually that is the only way to render suggestions.
Main goal of the library is gracefully render mentions in the `TextInput` component.

**Comment by Abhishek-Sankey** [comment]
@dabakovich can you plz provide a minimal structure for the same?

**Comment by dabakovich** [comment]
@Abhishek-Sankey I think the [example](https://github.com/dabakovich/react-native-controlled-mentions#example) has pretty basic structure.
As you can see `MentionSuggestions` is declared and written manually in that file.

**Comment by Abhishek-Sankey** [comment]
@dabakovich 
![Screenshot 1942-09-26 at 8 40 57 PM](https://user-images.githubusercontent.com/53463010/102505655-44547080-40a8-11eb-9460-15afc2d0da7e.png)
getting this error, tried every thing...
`import { Mentions, Suggestion } from 'react-native-controlled-mentions';
<Mentions
        value={this.state.mentionText}
        onChange={this.onChangeMention}
        placeholder="Type here..."
    >				
</Mentions>`

**Comment by dabakovich** [comment]
Thanks for reporting the bug. Should be fixed in v0.1.5

**Comment by dabakovich** [comment]
@Abhishek-Sankey do you have any other questions?
Feel free to create another issue if so.

**Comment by Abhishek-Sankey** [comment]
Havent tried it again...Will try again and let you know in case of any issues or bugs.
Thanks!

**Comment by Abhishek-Sankey** [comment]
@dabakovich 
onSelectionChange is not getting invoked...
![Screenshot 1942-09-27 at 5 52 22 PM](https://user-images.githubusercontent.com/53463010/102614183-cd77b000-4159-11eb-9c0f-27c0494f0bd1.png)
i was using TextInput there. Now, I've replaced that TextInput with the Mentions.

**Comment by dabakovich** [comment]
@Abhishek-Sankey Oh, I see. Actually, I'm overriding that method because of handling selection in the library. But if it's critical for you I can forward and call that method if it exists.

**Comment by dabakovich** [comment]
@Abhishek-Sankey can you open a new issue for that fix?

**Comment by dabakovich** [comment]
> @Abhishek-Sankey can you open a new issue for that fix?

Don't worry, I'll create now.

**Comment by Abhishek-Sankey** [comment]
thanks!

**Comment by dabakovich** [comment]
@Abhishek-Sankey You can try it now at v0.1.6

**Comment by Abhishek-Sankey** [comment]
thanks! tried the lib, works like charm!!!
I've some suggestions:
1. a style prop for the mentions, user can give his own style to the mention
2. a regEx prop...(for example - in my case, I've got an alphanumeric `id` which includes [a-z0-9-]
3. it'll be good to have hashTags and mentions in the same text input
Thanks again... :)

**Comment by dabakovich** [comment]
@Abhishek-Sankey thanks a lot for your response!
Please open issues for the suggestions.
