### ISSUE TITLE
Api calling using class component?

### ISSUE THREAD

**Issue by shahchirag2110** [dabakovich/react-native-controlled-mentions#72]
**I am using class component and now i need to called api from renderSuggestions so how i can do that with class component? I checked your answer but you used hooks for api calling which has userCallback and etc.**

I need to show suggestion of user something like instagram does but there is no way we can fix the position or change the direction from vertical to horizontal.
![mentions](https://user-images.githubusercontent.com/11793894/134551643-c8c26fa8-ed7d-47fd-a989-51ac21bb5902.png)

You done a good work on this library so need this little bit help more :)

**Comment by knilf-i-am** [comment]
Just render your suggestions in a horizontal view. Something like:

`function getSuggestions({ keyword, onSuggestionPress }) {
...
return (
    <ScrollView
        horizontal={ true }
        keyboardDismissMode="none"
        keyboardShouldPersistTaps="always"
        showsHorizontalScrollIndicator={ false }
        style={ style.suggestionContainer }
    >`

**Comment by knilf-i-am** [comment]
As for the custom position, have you played around with `position: "absolute"`?

**Comment by shahchirag2110** [comment]
@knilf-i-am need to set absolute position for scroll view or anywhere else?

**Comment by shahchirag2110** [comment]
@knilf-i-am @dabakovich I am using class component and now i need to called api from renderSuggestions so how i can do that with class component? I checked your answer but you used hooks for api calling which has userCallback and etc.
