### ISSUE TITLE
[Solution] Displaying Mentions Away from TextInput

### ISSUE THREAD

**Issue by swushi** [dabakovich/react-native-controlled-mentions#75]
## Problem
This library has one key pitfall, it has is the inability to render the suggestions component apart from the `TextInput`. This is the root of some difficult styling challenges. I can see from a number of issues on your repo that this is popular issue. I am writing my solution out as there has not been a great solution I've seen.

## Solution
Elevate the mention state up to a provider. 

This would essentially look like this:

### Parent Screen
```ts
<SuggestionsProvider>
  <Screen>
    <MentionInput />
    <Suggestions />
  </Screen>
</SuggestionsProvider>
```

### Suggestions Component
```ts
const { suggestions } = useSuggestions();
{suggestions.map(item => <Suggestion {...item} />) }

```
### Part Type Creator
You basically need to allow the suggestions provider to take in config for each respective trigger. My implementation for that looks like this:

```ts
export default function usePartTypeCreator() {
  const { setConfig, config } = useSuggestions();
  
  const createPartTypes = useCallback<
    (triggers: SupportedSuggestionTrigger[]) => PartType[]
  >(
    triggers =>
	triggers.map(trigger => ({
          trigger,
          textStyle: { fontWeight: 'bold' }, 
          allowedSpacesCount: 0,
          isInsertSpaceAfterMention: true,
          
          // Note: This is not directly rendering suggestions. It is just passing up null for render.
          // We are passing the data up to the provider which can then be consumbed from anywhere.
          renderSuggestions: props => {
	      if (config?.[trigger]?.keyword !== props.keyword) {
		setConfig(oldConfig => ({ ...oldConfig, [trigger]: props }));
	      }
	      return null;
          }
	})),
  [config]
);

	return createPartTypes;
}
```
Usage for that looks like:

```ts
const createPartTypes = usePartTypeCreator();
<MentionInput partTypes={createPartTypes('#', '@')} />
```

### SuggestionsProvider Interface
This is how I've exposed the provider for usage throughout the app.
```ts
export default function useSuggestions() {
  const suggestions = useContext(SuggestionContext);
  
  const mentions = suggestions.config?.['@'];
  const topics = suggestions.config?.['#'];
  
  return { ...suggestions, mentions, topics };
}

```

If anyone else decides to go down this rabbit hole, let me know. I have a working implementation in our production app, and would be happy to help.

**Comment by HHEntertainment** [comment]
@swushi  @dabakovich I think it is awesome suggetions!

**Comment by grooveslap** [comment]
@swushi Thanks you for your great solution. I am having some little difficulties implementing as you suggested above. So could you please share your working implementation in your production. Thank you in advance!

**Comment by swushi** [comment]
```tsx
import React, { createContext, useCallback, useState } from 'react';

import { useDebugLog } from 'hooks/debug/useDebugLog';
import { useRenderCounter } from 'hooks/debug/useRenderCounter';

import { SuggestionConfig } from 'hooks/providers/usePartTypeCreator';

const debug = false;
const debugLogs = false && debug;
const debugRenders = false && debug;
interface SuggestionContextConfig {
	config?: SuggestionConfig;
	setConfig: React.Dispatch<React.SetStateAction<SuggestionConfig | undefined>>;
	clearConfig: () => void;
}

export const SuggestionContext = createContext<SuggestionContextConfig>({} as SuggestionContextConfig);

/**
 * A provider that should wrap the screen that contains a `MentionInput`
 *
 * The purpose of this provider is to allow the suggestions component to
 * be rendered outside of the input. Currently it is forced to be attached directly to the
 * input, which is usually in a inconvenient location.
 *
 * @example
 * const suggestions = useSuggestions()
 *
 * <SuggestionsProvider>
 *   <Screen>
 *     <MentionInput />
 *
 *     // can separate suggestions now, was previously attached to the above component
 *     {suggestions && renderSuggestions()}
 *
 *   </Screen>
 * </SuggestionsProvider>
 */
const SuggestionsProvider: React.FC = ({ children }) => {
	useRenderCounter('SuggestionsProvider', debugRenders);
	const debugLog = useDebugLog('SuggestionsProvider', debugLogs);

	const [config, setConfig] = useState<SuggestionConfig>();

	const clearConfig = useCallback(() => {
		setConfig(undefined);
	}, []);

	return (
		<SuggestionContext.Provider
			value={{
				config,
				setConfig,
				clearConfig
			}}
		>
			{children}
		</SuggestionContext.Provider>
	);
};

export default SuggestionsProvider;
```

**Comment by grooveslap** [comment]
@swushi Thanks you so much! You're the man!

**Comment by aloukissas** [comment]
@swushi this is great! Can you perhaps share the type definition for `SuggestionConfig`? I _think_ I have it figured out, but it would help others

**Comment by swushi** [comment]
@aloukissas here is my type for `SuggestionConfig`

```typescript
type SupportedSuggestionTrigger = '@' | '#';

type SuggestionConfig = {
  [Property in SupportedSuggestionTrigger]?: MentionSuggestionsProps | undefined;
};
```

This mapped type essentially creates this type:

```typescript
type SuggestionConfig = {
  '@'?: MentionSuggestionsProps;
  '#'?: MentionSuggerstionsProps;
};
```
I am not familiar with `jotai` myself, but after reading through their docs it looks like a great library. Is it not using providers under the hood?

**Comment by aloukissas** [comment]
Awesome thanks @swushi. I believe it's using react context under the hood. It's really a lightweight implementation of Facebook's Recoil. Very happy with it.

**Comment by TheFrostage** [comment]
Hey @swushi, I am having so much trouble with a similar problem. 2 sibling components, need to handle `onPressSuggestion` appropriately. I'm having a hard time wrapping my head around how should the on press handler of a suggestion look like. I've seen that in the MentionInput it's parsing the text by using internal state, but I don't understand how to move it away from there correctly. Could you please help me by showing our onPress handler of a suggestion component?

**Comment by dabakovich** [comment]
Hi @swushi and other participants! Thank all for your feedbacks and especially for participating all in searching for solution of this issue.

Finally, I got a few free days for supporting this package.

Your suggestion with using context inspired me to re-think the functionality with rendering suggestions. In fact, we have no need to render it in the `MentionInput`. And more – we don't need the `MentionInput` component as well. It's enough to provide just a few props directly to the `TextInput` component.

So, I'd be glad to say that a new major v3 release is coming, and this issue is one of the main updates 🎉.

Now you will be able to use hook for control mention state. The main idea – suggestions rendering now will be fully controlled by user and is extracted from `MentionInput` component.

You can find an example of this here: https://github.com/dabakovich/react-native-controlled-mentions/blob/3.0.0-feat-use-mentions/example/mentions-app.tsx#L90

To install this and play by yourself, please use next commands:
```
yarn add react-native-controlled-mentions@alpha
// or
npm install --save react-native-controlled-mentions@alpha
```
I'll be happy to get some feedback from you before the major update will be released.

**Comment by hirbod** [comment]
@dabakovich these are great news. Gonna try that very soon!

**Comment by dabakovich** [comment]
I'm closing the issue due to the lack of new questions and activity. You are welcome to add comments or create a new issue if you'll get new questions.
