### ISSUE TITLE
 Highlighting the mention text whilst typing

### ISSUE THREAD

**Issue by oreoluwade** [dabakovich/react-native-controlled-mentions#79]
Could anyone help with the possibility of highlighting the mention text as it is being typed (before selection) and then the highlight disappears as soon as a selection is made from the suggestions?

Basically, this is what I am looking to achieve for example:

-  User types “#” on their keyboard
- Text directly after “#” is highlighted in a soft gray
- Two spaces cancels highlighting and tag is not made
- If one of the suggestions is selected, it is then colored blue

**Comment by dabakovich** [comment]
Hello, thanks for your feedback. Is your issue still actual?

As a suggestion – you can add another part type with pattern for highlighting plain hashtags (`/#(.)+/gi`) and it should highlight your hashtag before you will select some from list.

**Comment by dabakovich** [comment]
Duplicates #58.

Please, continue the discussion in that issue.
