### ISSUE TITLE
display @taggedName without the '@' symbol.  

### ISSUE THREAD

**Issue by vegerot12** [dabakovich/react-native-controlled-mentions#81]
I am trying to display the mentioned name without the @ symbol . The mentioned name gets highlighted but the @ symbol shouldnt be visible. 
Eg :
current display : hi @**Mary**
required : hi **Mary** 

If i use string slice in text tag then the mentions are getting lost in subsequent on change 
` const getFormattedText = text => {
    // console.log('text', text);
    if (text.startsWith('@')) {
      setDisplayValue();
      return text.slice(1);
    }
    return text;
  };`

`<Text>
          {parts.map(({ text, partType, data }, index) =>
            partType ? (
              (console.log(text, 'text'),
              (
                <Text key={`${index}-${data?.trigger ?? 'pattern'}`} style={partType.textStyle ?? defaultMentionTextStyle}>
                  {getFormattedText(text)}
                </Text>
              ))
            ) : (
              <Text key={index}>{text}</Text>
            )
          )}
        </Text>`

Is there any way to achieve that

**Comment by jagataess** [comment]
@vegerot12  Can you please share how did you fix it?
