### ISSUE TITLE
How to make suggestion bottom 

### ISSUE THREAD

**Issue by khanh21011999** [dabakovich/react-native-controlled-mentions#82]
I know that we can make suggestion box not inside TextInput by add `position:"absolute"` but it not useful if i want the mention in bottom like this image, so how can we do that?
<img width="257" alt="image" src="https://user-images.githubusercontent.com/37074707/156098682-972ebe4f-4155-499a-af35-b7a593ee586a.png">

**Comment by vegerot12** [comment]
use the prop isBottomMentionSuggestionsRender within parttypes . it works

**Comment by khanh21011999** [comment]
Hey @vegerot12 , i still don't know how to use that, i use like this, but had no effect

```javascript
 <MentionInput
          isBottomMentionSuggestionsRender
          partTypes={[
            {
              trigger: '@', // Should be a single character like '@' or '#'
              renderSuggestions: renderMentionSuggestions,
              textStyle: { fontWeight: 'bold', color: 'blue' } // The mention style in the input
            }
          ]}
          onChange={(text) => {
            setRemainContentText(400 - text.length);
          }}
          maxLength={400}
          multiline
          style={styles.contentTextInput}
          placeholder='Add a description...'
        />```

**Comment by dabakovich** [comment]
Hi @khanh21011999! Thanks for your feedback. As @vegerot12 mentioned, you can use `isBottomMentionSuggestionsRender` property. Please, see the prop explanation [here](https://github.com/dabakovich/react-native-controlled-mentions#mentionparttype-type-props).

So, your code should become:
```javascript
<MentionInput
  partTypes={[
    {
      trigger: '@', // Should be a single character like '@' or '#'
      renderSuggestions: renderMentionSuggestions,
      textStyle: { fontWeight: 'bold', color: 'blue' }, // The mention style in the input
      isBottomMentionSuggestionsRender: true,
    }
  ]}
  onChange={(text) => {
    setRemainContentText(400 - text.length);
  }}
  maxLength={400}
  multiline
  style={styles.contentTextInput}
  placeholder='Add a description...'
/>
```

**Comment by dabakovich** [comment]
Closing the issues. Please, feel free to re-open it if you will get any other related questions.

Duplicates #27
