### ISSUE TITLE
mentionRegEx in the documentation is different from mentionRegEx used in the package

### ISSUE THREAD

**Issue by FarishLoy** [dabakovich/react-native-controlled-mentions#86]
mentionRegEx = /(?<original>(?<trigger>.)\[(?<name>[^[]*)]\((?<id>[^(]*)\))/gi // in package

mentionRegEx = /(?<original>(?<trigger>.)\[(?<name>([^[]*))]\((?<id>([\d\w-]*))\))/gi; //in documentation

i don't know if this was an error or intentional but trying to parse the value with string.match() function I had to use the RegEx expression in the package.

**Comment by dabakovich** [comment]
Thanks for your feedback!

Yep, in docs we have outdated regex declaration, it will be fixed in the next release.

Anyway, you can import `mentionRegEx` from the `react-native-controlled-mentions` package.

**Comment by dabakovich** [comment]
Going to close the issue. Feel free to re-open it if you will get any additional related questions.
