### ISSUE TITLE
Suggestions-

### ISSUE THREAD

**Issue by Abhishek-Sankey** [dabakovich/react-native-controlled-mentions#9]
Awesome library....works like charm!!!
I've some suggestions:
1. a style prop for the mentions, user can give his own style to the mention
2. a regEx prop...(for example - in my case, I've got an alphanumeric id which includes [a-z0-9-]
3. it'll be good to have hashTags and mentions in the same text input
Thanks again... :)

**Comment by dabakovich** [comment]
Added 1 and 2 points to v0.1.7.
Need to make some code refactor to implement 3. Plan to work on it later.

**Comment by Abhishek-Sankey** [comment]
Thanks!
Should I close this issue?

**Comment by dabakovich** [comment]
You can close it and open another one just for hashtags feature if you wish.
Thanks!

**Comment by snamstorm** [comment]
Can we have URL formatting as well please? :)

**Comment by dabakovich** [comment]
@snamstorm, actually yes, but does it make sense? Because we are still not able to add the "onPress" handler here. Anyway, it's not the main goal for the "mentions" library.
But I plan to add different text formatting (bold, italic, links, etc) to the input later.

**Comment by Abhishek-Sankey** [comment]
@dabakovich can you also update the readme file? As far as I can understand from changes, is that I need to pass an array of objects and each object will be having all keys like mentionStyle, triggeer...etc.
Plz correct me if i'm wrong.
Also, it'll be a plus point if we also have URL formatting. Afterall, it's a text input and user can add/type anything he/she wants.

**Comment by dabakovich** [comment]
@Abhishek-Sankey you can check the updated readme for multiple mention types on the [multiple-mention-type-feature](https://github.com/dabakovich/react-native-controlled-mentions/tree/multiple-mention-type-feature) branch. It's the alpha release yet, you can play with it installing 1.0.0-0 using npm.

I'll think about the URL formatting later.

And yes, now you can add hashtag mention type!🎉

**Comment by snamstorm** [comment]
@dabakovich 

> @snamstorm, actually yes, but does it make sense? Because we are still not able to add the "onPress" handler here. Anyway, it's not the main goal for the "mentions" library.
> But I plan to add different text formatting (bold, italic, links, etc) to the input later.

For us, we use one component for text input which handles both Hashtags and URLs (we currently use react-native-parsed-text for this) since when a person makes a post, they can have both options in a post. We are adding a 3rd option for mentions which your lib handles very well. Would be very useful to have all 3 options in one lib with on text input

**Comment by dabakovich** [comment]
@snamstorm got it. Can you create a new issue and describe the requirements for that feature? Should we just highlight any link or should we hide a link into some text like in MD (`[text](http://link.com)`) and show only highlighted 'text' in TextInput. It would be great to provide some screenshot examples. Thanks!

**Comment by Abhishek-Sankey** [comment]
@dabakovich will play with the alpha release and let you know if in case of any bugs or issues found.
Thanks! 😄

**Comment by snamstorm** [comment]
> @snamstorm got it. Can you create a new issue and describe the requirements for that feature? Should we just highlight any link or should we hide a link into some text like in MD (`[text](http://link.com)`) and show only highlighted 'text' in TextInput. It would be great to provide some screenshot examples. Thanks!

@dabakovich thanks - created an issue here https://github.com/dabakovich/react-native-controlled-mentions/issues/13

**Comment by Abhishek-Sankey** [comment]
> @Abhishek-Sankey you can check the updated readme for multiple mention types on the [multiple-mention-type-feature](https://github.com/dabakovich/react-native-controlled-mentions/tree/multiple-mention-type-feature) branch. It's the alpha release yet, you can play with it installing 1.0.0-0 using npm.
> 
> I'll think about the URL formatting later.
> 
> And yes, now you can add hashtag mention type!🎉

@dabakovich tested the hashTags and it's working as expected.
Thanks again!

**Comment by dabakovich** [comment]
> Also, it'll be a plus point if we also have URL formatting

@Abhishek-Sankey custom pattern formatting (like URLs) added to v2.0.0.
