### ISSUE TITLE
get how mention in string

### ISSUE THREAD

**Issue by fukemy** [dabakovich/react-native-controlled-mentions#94]
hi, for example i have a string text:

 `@[demo5](d3f0c3cd-f363-4303-8761-8e190f054be3)  want to talk with @[demo8](8dbafd40-b86f-490a-828d-d11dfe221b43)`

now i want to extract into :

```
[
{
name: 'demo5',
id : 'd3f0c3cd-f363-4303-8761-8e190f054be3',
},
{
name: 'demo8',
id : '8dbafd40-b86f-490a-828d-d11dfe221b43',
}
]
```

can u provide me how to do it, thanks so much

**Comment by ydhnwb** [comment]
i'm looking for this also. have you solve it @fukemy ? because the docs not giving the example

**Comment by fukemy** [comment]
ok, using this
```
replaceMentionValues(value, ({id, name}) => {
   //here you got id, name do it with your self
   return ...
})
```
