### ISSUE TITLE
Performance Issue 

### ISSUE THREAD

**Issue by SafdarSikander** [dabakovich/react-native-controlled-mentions#97]
how to use large data like I am using 7000 users for the suggestions it is lagging, also how we can fetch suggestions from API with pagination.

**Comment by dabakovich** [comment]
Please, try to play with new alpha v3 version of this library with redesigned flow for rendering suggestions. Maybe it will help you.

You can find examples of using new v3 release here: https://github.com/dabakovich/react-native-controlled-mentions/blob/3.0/example/mentions-functional-component.tsx

To test `alpha` pre-release please, install the library using next command:
```
yarn add react-native-controlled-mentions@alpha
// or
npm install --save react-native-controlled-mentions@alpha
```

**Comment by fukemy** [comment]
for 7000+ data, please use RecyclerListView + v3
