### ISSUE TITLE
IS THIS BUG? =>  conflict click with keyboardShouldPersistTaps(android only)

### ISSUE THREAD

**Issue by fukemy** [dabakovich/react-native-controlled-mentions#98]
Hi, with IOS, only 1 click to select user from mentionView, but in Android, i need to ***click 3 times***, can u help? I dont know why, please see the below video:

https://user-images.githubusercontent.com/8202437/185751258-48219e9e-f569-46a4-a61d-37baf391d907.mov

**Comment by fukemy** [comment]
@dabakovich can u take a look?

**Comment by fukemy** [comment]
@imhazige i need to put keyboardShouldPersistTaps inside mentionView scroll

**Comment by imhazige** [comment]
Hey, @fukemy,

Thank you, but I did not find any scoll view in the source code, are you  using version 3?

**Comment by fukemy** [comment]
hi, i am using version 3 to avoid using MentionInput directly. About scrollView u can go to the source code to find it.

For example, wrap this line by scrollView:
https://github.com/dabakovich/react-native-controlled-mentions/blob/8b286da2bec38ee3a02f7239af474a6e46708ad3/src/components/mention-input.tsx#L129-L136

**Comment by imhazige** [comment]
Hey, @fukemy 

Thank you so much, it is keyboardShouldPersistTaps problem.

Actually I also need render the suggestion outside the input, I made a workaround based on v2
```javascript
renderSuggestions: ({ keyword, onSuggestionPress }) => {
                  // can not use the library's ui, android bug: will have @ as keyword
                  if (keyword === mentionKeyworkRef.current || keyword === '@')
                    return;
                  // undefined mean no @ typed
                  mentionKeyworkRef.current = keyword;
                  onSuggestionPressRef.current = onSuggestionPress;
                  setShowMention(keyword !== undefined);

                  return null;
                }
```

**Comment by fukemy** [comment]
good job bro
