### ISSUE TITLE
[Bug] Visual issue

### ISSUE THREAD

**Issue by fseguraLanding** [dabakovich/react-native-controlled-mentions#99]
Hi! I hope you are well.
I'm having a few visual issues with the render function of the MentionInput.
In my case, the trigger character is a '@', and I detected that the renderSuggestions function is rendering 4 times every time I insert a new character. The first time it comes as undefined and that's causing the 'flashing' bug.

Please let me know if you need any other information!

Thanks!

https://user-images.githubusercontent.com/106693705/187484026-9f0b7f4d-3b4d-44a4-93f0-dfc24d7bbe74.mov

**Comment by AnushavanMelon** [comment]
In my case keyword:undefined happend when TextInput is multiline.

**Comment by andreirat** [comment]
@fseguraLanding @AnushavanGhulyan-melon  I'm having the same issue. I can confirm that it's because of the `multiline` prop. Did you find a fix for this?

**Comment by AnushavanGhulyan-melon** [comment]
@andreirat nope

**Comment by marikannantgi** [comment]
I am also facing this disturbance Please [fix] this Bug

**Comment by dabakovich** [comment]
Hi all! Please refer to the [comment](https://github.com/dabakovich/react-native-controlled-mentions/issues/55#issuecomment-1633995138) in #55.

You are welcome to ask additional questions if they arise.

**Comment by dabakovich** [comment]
I'm closing this issue as there have been no further questions.
